### ISSUE TITLE
ianmuchina.com

### ISSUE THREAD

**Issue by ianmuchina** [kevquirk/512kb.club#356]
Link to GTMetrix results: https://gtmetrix.com/reports/ianmuchina.com/KvZOGv1P/

```yml
- domain: ianmuchina.com
  url: https://ianmuchina.com
  size: 13.6
```
